global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'GteamGteamG@gmail.com'  # 여기에 수신하고자 하는 이메일 주소 입력
    from: 'GteamGteamG@gmail.com'  # 발신자 이메일 주소, 실제 사용할 주소로 변경 가능
    smarthost: 'smtp.gmail.com:587'  # 사용하는 메일 서버의 주소와 포트
    auth_username: 'GteamGteamG@gmail.com'  # 메일 서버 로그인 ID
    auth_password: 'Gteam123777!'  # 메일 서버 로그인 비밀번호