version: '3.3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-tier

  celery:
    build: ./backend
    container_name: celery_worker
    command: celery -A myproject worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
    env_file:
      - ./backend/.env 
    depends_on:
      - rabbitmq
      - mysqldb
    volumes:
      - ./backend:/backend
    networks:
      - app-tier

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - react

#  react:
#    build:
#      context: ./frontend
#    container_name: react
#    stdin_open: true
#    command: sh -c "yarn dev"
#    ports:
#      - 5173:5173
#    volumes:
#      - ./frontend:/app/frontend

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - sql-db:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uadmin', '-proot']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - mysqldb
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    networks:
      - app-tier

  django:
    build:
      context: ./backend
    container_name: django
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/backend/
      - sql-db:/var/lib/mysql
    depends_on:
      - mysqldb
    networks:
      - app-tier
    restart: always

volumes:
  rabbitmq_data:
  sql-db:

networks:
  app-tier:
    driver: bridge
