global:
  scrape_interval: 15s # 기본적으로 15초마다 스크랩합니다.
  evaluation_interval: 15s # 15초마다 규칙을 평가합니다.

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - 'alertmanager:9093' # Alertmanager의 호스트 이름과 포트를 여기에 추가합니다.

rule_files:
  - 'prometheus.rules.yml' # 경고 규칙 파일입니다.

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'django'
    static_configs:
      - targets: ['django:8001']
